#pragma once

// IOCTL codes shared with the HidHide driver (Nefarius).
// https://docs.nefarius.at/projects/HidHide/API-Documentation/

#include <Windows.h>

#ifndef IOCTL_HIDHIDE_GET_WHITELIST
#define IOCTL_HIDHIDE_GET_WHITELIST CTL_CODE(32769, 2048, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_HIDHIDE_SET_WHITELIST CTL_CODE(32769, 2049, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_HIDHIDE_GET_BLACKLIST CTL_CODE(32769, 2050, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_HIDHIDE_SET_BLACKLIST CTL_CODE(32769, 2051, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_HIDHIDE_GET_ACTIVE    CTL_CODE(32769, 2052, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_HIDHIDE_SET_ACTIVE    CTL_CODE(32769, 2053, METHOD_BUFFERED, FILE_READ_DATA)
#endif

inline constexpr wchar_t kHidHideControlDevicePath[] = L"\\\\.\\HidHide";
